### ISSUE TITLE
[Databricks] handshake_failure when sending logs

### ISSUE THREAD

**Issue by ImpSy** [datamechanics/delight#1]
## What

When trying to send logs from a databricks cluster with the init-script found in the documentation we receive this error:
```scala
20/11/06 17:11:55 WARN DelightStreamingConnector: Failed to send heartbeat to https://api.delight.datamechanics.co/collector/heartbeat: Received fatal alert: handshake_failure
javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
	at sun.security.ssl.Alert.createSSLException(Alert.java:131)
	at sun.security.ssl.Alert.createSSLException(Alert.java:117)
	at sun.security.ssl.TransportContext.fatal(TransportContext.java:311)
	at sun.security.ssl.Alert$AlertConsumer.consume(Alert.java:293)
	at sun.security.ssl.TransportContext.dispatch(TransportContext.java:185)
	at sun.security.ssl.SSLTransport.decode(SSLTransport.java:156)
	at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1197)
	at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1106)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:398)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:370)
	at org.apache.http.conn.ssl.SSLSocketFactory.createLayeredSocket(SSLSocketFactory.java:573)
	at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:557)
	at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:414)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:180)
	at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:326)
	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:610)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:445)
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:835)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
	at co.datamechanics.delight.DelightStreamingConnector.sendRequest(DelightStreamingConnector.scala:79)
	at co.datamechanics.delight.DelightStreamingConnector.sendHeartbeat(DelightStreamingConnector.scala:101)
	at co.datamechanics.delight.DelightStreamingConnector$$anon$2.run(DelightStreamingConnector.scala:276)
```

#### Init Script used
```bash
#!/bin/bash

SCALA_VERSION="2.12"
ACCESS_TOKEN="<replace-with-your-access-token>"

SPARK_DEFAULTS_FILE="/databricks/driver/conf/00-custom-spark-driver-defaults.conf"

if [[ $DB_IS_DRIVER = "TRUE" ]]; then
        wget --quiet \
          -O /mnt/driver-daemon/jars/delight.jar \
          https://oss.sonatype.org/content/repositories/snapshots/co/datamechanics/delight_$SCALA_VERSION/latest-SNAPSHOT/delight_$SCALA_VERSION-latest-SNAPSHOT.jar

        cat > $SPARK_DEFAULTS_FILE <<- EOF
        [driver] {
          "spark.extraListeners" = "com.databricks.backend.daemon.driver.DBCEventLoggingListener,co.datamechanics.delight.DelightListener"
          "spark.delight.accessToken.secret" = "$ACCESS_TOKEN"
        }
EOF
fi
```

### Issue with Let's encrypt certificate and Java

cf https://stackoverflow.com/questions/34110426/does-java-support-lets-encrypt-certificates

We tried add let's encrypt certificates Java Truststore

With the following script
```bash
KEYSTORE_PWD="changeit"

cacert_path() {
    local jvm=$1
    path="/usr/lib/jvm/$jvm/jre/lib/security/cacerts"
    echo "$path"
}

certificates=(
    isrgrootx1
    isrg-root-x2
    letsencryptauthorityx3
    lets-encrypt-x3-cross-signed
    lets-encrypt-r3
    lets-encrypt-r3-cross-signed
    lets-encrypt-e1
)

for i in "${certificates[@]}"; do
    wget --quiet "https://letsencrypt.org/certs/${i}.der"
    for jvm in $(ls /usr/lib/jvm); do
        keystore_path=$(cacert_path "$jvm")
        if [ -f "$keystore_path" ]; then
            echo "Importing certificate $i into $keystore_path"
            keytool -import -keystore $keystore_path -storepass $KEYSTORE_PWD -noprompt -trustcacerts -alias $i -file ${i}.der
        fi
    done
done
```

### Force utilisation of TLSv1.2

Adding the following config doesn't change a thing (even the verbosity of logs)
```scala
[driver] {
    "spark.driver.extraJavaOptions" = "-Djdk.tls.client.protocols=TLSv1.2 -Dhttps.protocols=TLSv1.2 -Djavax.net.debug=ssl:handshake:verbose"
}
```

**Comment by jrj-d** [comment]
Solved in 59ce13d71b5c867ff5bc709af9cb775013dbb6a1
